[font]
size = 18

[font.bold]
family = "Inconsolata"
style = "Bold"

[font.italic]
family = "Inconsolata"
style = "Italic"

[font.normal]
family = "Inconsolata"
style = "Light"

[scrolling]
history = 20000
multiplier = 3

[window.padding]
x = 2
y = 2

[window]
option_as_alt = "Both"
